"""empty message

Revision ID: 9c57855383df
Revises: 4767045563ac
Create Date: 2022-10-09 14:59:44.443974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c57855383df'
down_revision = '4767045563ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('descripition', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'descripition')
    # ### end Alembic commands ###
